# Generated by Django 5.1.2 on 2024-10-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'verbose_name': 'Servidor', 'verbose_name_plural': 'Servidores'},
        ),
    ]
